name: Jekyll action test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: "helaili/jekyll-action@master"
      name: build and deploy
      env:
          SRC = "sample_site"
          secrets = [${{ secrets.PERSONAL_TOKEN }}]
