name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
    - name: Download azcopy
      run: "wget -O ../azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux"

    - name: extract azcopy
      run: tar -xf ../azcopy.tar.gz -C ../
 
    - name: copy file
      run: "../azcopy_*/azcopy sync \"${{github.workspace}}/_site/\" \"https://jekylltest.blob.core.windows.net/web/${{secrets.sas_key}}\" --delete-destination=true"
